__TYPEFINITY_GLOBS       = * */* */*/* */*/*/* */*/*/*/* */*/*/*/*/* */*/*/*/*/*/* */*/*/*/*/*/*/* */*/*/*/*/*/*/*/*
__TYPEFINITY_TS          = $(wildcard $(foreach glob, $(__TYPEFINITY_GLOBS), src/$(glob).ts))
__TYPEFINITY_JS_REQUIRED = $(patsubst src/%.ts, dist/%.js, $(__TYPEFINITY_TS))
__TYPEFINITY_JS_EXISTING = $(wildcard $(foreach glob, $(__TYPEFINITY_GLOBS), dist/$(glob).js))
__TYPEFINITY_JS_OBSOLETE = $(filter-out $(__TYPEFINITY_JS_EXISTING), $(__TYPEFINITY_JS_REQUIRED))


$(TYPEFINITY_COMPILE) : $(__TYPEFINITY_TS)
	echo Compiling...
	tsc
	touch $@
