#!/usr/bin/env bash

set -o pipefail

function __lp_test() {
    unset -f __lp_test
    local TEST_REPORTER
    if [[ -f .launchpad/test-reporter-node-tap.awk ]]; then
        TEST_REPORTER=.launchpad/test-reporter-node-tap.awk
    elif [[ -f test-reporter-node-tap.awk ]]; then
        TEST_REPORTER=test-reporter-node-tap.awk
    else
        echo "ERROR: .launchpad/test-reporter-node-tap.awk does not exist" >&2
        return 1
    fi
    node --test --test-concurrency=true --enable-source-maps --test-reporter=tap "$@" | awk -f "${TEST_REPORTER}"
}

__lp_test "$@"

