#!/usr/bin/env bash

if [[ -d "../.launchpad" ]]; then
    cd ..
fi

if [[ ! -d "./.launchpad" ]]; then
    echo "⛔ ERROR: .launchpad/uplift must be run from the project root directory" >&2
    exit 1
fi

echo "Uplifting the project..."
echo ""

if ! launchpad uplift "$@"; then
    echo "" >&2
    echo "⛔ ERROR: The uplift has failed" >&2
    exit 1
fi
